version: "3.3"
services:
  spark-master:
    image: spark_lab/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    command: "/start-master.sh"
  spark-worker:
    image: spark_lab/spark:latest
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    command: "/start-worker.sh"
  mysql-db:
    image: mysql:latest
    ports:
      - "3336:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MySQL_PASSWORD=password
      - MYSQL_DATABASE=testdb
  postgres-db:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_ROOT_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=testdb
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
